package pgdswd.lingerie;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import java.net.URL; 
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;


/**
 * Demonstrates the lingerie App
 * @author matjele7@gmail.com
 */
public class LingerieCatalogue extends javax.swing.JFrame {
    
    String[] imgFilesPath = {"lingerie_004681.png", "lingerie_004682.png", "lingerie_004683.png", 
          "lingerie_004684.png","lingerie_004685.png", "lingerie_004686.png", 
          "lingerie_004687.png", "lingerie_004688.png", "lingerie_004689.png", "lingerie_004690.png" };
    String[] htmlFilesPath = {"004681.html", "004682.html", "004683.html",
            "004684.html", "004685.html", "004686.html", "004687.html",
            "004688.html", "004689.html", "004690.html" };
    int count;
    
    String s = "Teboho Alfred Matjele\n\nmatjele7@gmail.com\nteboho.matjele@younglings.africa"
            + "\n\n\nthe Developer of this lingerie system\n_____________________________\n| This is not a porn system |"
            + "\n''''''''''''''''''''''''''''''''''''''''''''''''''''''''''";
      
    /**
     * Creates new form LingerieCatalogue
     */
    public LingerieCatalogue() {
        initComponents();
        jepCatalogueDetails.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepCatalogueDetails = new javax.swing.JEditorPane();
        jpImageIcon = new javax.swing.JPanel();
        lblCatalogueImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCatalogue = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lingerie Catalogue");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Catalogue Details"));

        jScrollPane1.setViewportView(jepCatalogueDetails);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jpImageIcon.setBorder(javax.swing.BorderFactory.createTitledBorder("Catalogue Image"));

        lblCatalogueImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pgdswd/lingerie/images/GradImage.png"))); // NOI18N

        javax.swing.GroupLayout jpImageIconLayout = new javax.swing.GroupLayout(jpImageIcon);
        jpImageIcon.setLayout(jpImageIconLayout);
        jpImageIconLayout.setHorizontalGroup(
            jpImageIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCatalogueImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpImageIconLayout.setVerticalGroup(
            jpImageIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCatalogueImage)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCatalogue.setText("First Catalogue Item");
        btnCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogueActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCatalogue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnCatalogue))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void changeLingerie(){
        //images/lingerie_00 + list[count] + .png
        ImageIcon imgIcon = createImageIcon("images/" + imgFilesPath[count]);
        //html/00 + list[count] + .html
        
        BufferedImage bf = new BufferedImage(
          imgIcon.getIconWidth(),
          imgIcon.getIconHeight(),
          BufferedImage.TYPE_INT_RGB);
        
        JLabel img = new JLabel(imgIcon);
        
        
        URL htlmUrl = createFileUrl("html/" + htmlFilesPath[count]);
        if(bf != null){
          try{
            lblCatalogueImage.setIcon(imgIcon);
            
            if(htlmUrl != null){
              jepCatalogueDetails.setPage(htlmUrl);
            }else{
              jepCatalogueDetails.setPage(createFileUrl(" "));
            }
          }catch(IOException ex){
            javax.swing.JOptionPane.showMessageDialog(null, "File not found", "Error", 0);
          }
          
          if(count == 9){
             btnCatalogue.setText("First Catalogue Item");
            count = 0;
          }else{
              btnCatalogue.setText("Next Catalogue Item");
              ++count;}
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "No image found", "Error", 0);
        }
    }
    
    
    private void btnCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogueActionPerformed
        changeLingerie();
    }//GEN-LAST:event_btnCatalogueActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if(showConfirmDialog(null, "Are you sure you want to close?", "Lingerie Systems Close", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnExitActionPerformed
    
    /**
     * A function createImageIcon of the lingerie
     * @param path a string path to the lingerie icon
     * @return the lingerie image icon
     */
    private ImageIcon createImageIcon(String path)
    {
        URL imgPath = getClass().getResource(path);
        if(imgPath != null){
            return new ImageIcon(imgPath);
        }
        doMsg(path);
        return null;
    }  

    /**
     * A function createFileUrl of the html file with details of the lingerie
     * @param path a string path to the html file
     * @return the lingerie html file
     */
    private URL createFileUrl(String path){
        URL url = getClass().getResource(path);
        if(url == null){
            doMsg(path);
        }
        return url;
    }
  
    private void doMsg(String path){
        javax.swing.JOptionPane.showMessageDialog(null, "The path to " + path + " is incorect", "Error!", 0);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LingerieCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LingerieCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LingerieCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LingerieCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //ImageIcon c = createImageIcon();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LingerieCatalogue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogue;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane jepCatalogueDetails;
    private javax.swing.JPanel jpImageIcon;
    private javax.swing.JLabel lblCatalogueImage;
    // End of variables declaration//GEN-END:variables
}



